### PR TITLE
reform templates

### PR DESCRIPTION
**Pull request by sophiesongge**

### CODE REVIEW

**Review by laurianed — APPROVED** [review]

**Review by marcocast — COMMENTED** [review]
Why the 02_task_dependencies.xml changed the name into /02_task_dependency.xml  ?

**Comment by sophiesongge** [comment]
image
Because in the job descriptions, the name is 02_task_dependency, so, when I export it, it automatically changed to that one. I can change it back if needed.

**Comment by sophiesongge** [comment]
image

@marcocast 
Because in the job descriptions, the name is 02_task_dependency, so, when I export it, it automatically changed to that one. I can change it back if needed.

**Comment by marcocast** [comment]
@sophiesongge No it looks better what you did. 👍

**Pull request merged**
